main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
author: Lauriichan
api-version: 1.13

commands:
  items:
    description: Manage the ItemUI
    aliases: [item, itemui, iui]